name: end-to-end

on:
  workflow_dispatch: # Activate this workflow manually
  schedule:
    - cron: "0 0 * * 1"

env:
  PYTHON_VERSION: "3.10"
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  
jobs:
  e2e:
    timeout-minutes: 60
    strategy:
      fail-fast: false  # Avoid cancelling the others if one of these fails


    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies used in e2e tests
      run: pip install requests pytest

    - name: Run multi-container application (Elasticsearch + REST API)
      run: docker-compose up -d

    - name: Run tests
      run: pytest e2e/test_application.py