name: Scan for Secrets

on: 
  pull_request:
  push:
    branches:
      - main
      - master
  
jobs:
  scan-for-secrets:
    name: Scan for secrets
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install gitleaks
        run: wget -O - https://github.com/gitleaks/gitleaks/releases/download/v8.16.1/gitleaks_8.16.1_linux_x64.tar.gz | tar -xz
      - run: ./gitleaks detect --log-opts "${{  github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}"
        if: github.event_name == 'pull_request'
      - run: ./gitleaks detect --log-opts "${{  github.event.before }}..${{ github.event.after }}"
        if: github.event_name == 'push'
