name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "**.py"
      - "**/pyproject.toml"

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install pacage
        run: pip install .[dev]

      - name: Mypy
        run: |
          mkdir .mypy_cache/
          mypy --install-types --non-interactive --ignore-missing-imports rest_api/

  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install package
        run: pip install .[dev]

      - name: Pylint
        run: pylint -ry -j 0 rest_api/

  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install package
        run: pip install .[dev]

      - name: Check status
        run: |
          if ! black rest_api/ --check; then
            git status
            echo "###################################################################################################"
            echo "# "
            echo "# CHECK FAILED! Black found issues with your code formatting."
            echo "# "
            echo "# Either:"
            echo "# 1. Run Black locally before committing:"
            echo "# "
            echo "#     pip install .[dev]"
            echo "#     black ."
            echo "# "
            echo "# 2. Install the pre-commit hook:"
            echo "# "
            echo "#     pre-commit install"
            echo "# "
            echo "# 3. See https://github.com/deepset-ai/rest_api/blob/main/CONTRIBUTING.md for help."
            echo "# "
            echo "# If you have further problems, please open an issue: https://github.com/deepset-ai/rest_api/issues"
            echo "# "
            echo "##################################################################################################"
            exit 1
          fi

  tests:
    name: Tests / ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install package
        run: pip install .[dev]

      - name: Run
        run: hatch run cov
